### ISSUE TITLE
Blockquote style causes overflow on x-axis

### ISSUE THREAD

**Issue by andrewdoro** [MaximeHeckel/blog.maximeheckel.com#525]
Your Blockquote component from the design-system has `width:100vw`, causing overflow on pages that have height bigger than `100vh`.
[Blockquote style](https://github.com/MaximeHeckel/design-system/blob/main/src/components/Blockquote/Blockquote.styles.tsx#L11)

![Screenshot 2022-05-23 160205](https://user-images.githubusercontent.com/17547035/169825431-186186d0-9f0f-4b0c-9444-81de24024a6d.png)

**Comment by MaximeHeckel** [comment]
Yeah there's sadly no straightforward solution to this, kind of a bummer. I'll try to see if I can remove the 100vw and rely on grid-column instead, but with my current layout that's not a solution I think

**Comment by MaximeHeckel** [comment]
Best I could do for now would be to hide horizontal scrolling on the blog itself

**Comment by andrewdoro** [comment]
The way i fixed this problem in my blog was by adding a `calc(100vw-17px)` for desktop with tailwind, but it breaks when using a tablet. The more complex solution would be to calculate the scroll-width in an useEffect and then subtract.

**Comment by MaximeHeckel** [comment]
took the time to fix this in the design system: https://github.com/MaximeHeckel/design-system
