### ISSUE TITLE
How to Change the blog post slug form /post to /blog in the permaurl

### ISSUE THREAD

**Issue by sarmadgardezi** [MaximeHeckel/blog.maximeheckel.com#564]
How to Change the blog post slug form /post to /blog in the permaurl i,e domain.com/post/abc to domain.com/blog/abc

**Comment by MaximeHeckel** [comment]
That's more a Next.js question: just rename the `posts` folder under `pages` to whatever you want

Note: I would not advise using my code directly as your blog as my personal design system dependency will most likely break your blog without notice whenever I do refactors/updates 😅

**Comment by sarmadgardezi** [comment]
thankyou sir.
